apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-key
  namespace: {{ default "telegraf" .Values.namespace }}
data:
  .dockerconfigjson: {{ default "ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5ma2UuZnB0Y2xvdWQuY29tIjogewoJCQkiYXV0aCI6ICJlSEJzWVhRdFpHVnRiMEJtY0hSamJHOTFaQzVqYjIwNmFXcHJXVTFQY1hST2REbEhkMkozVWxsRWVuSmplVTFDUWxOdVJuRnVURkU9IgoJCX0KCX0KfQo=" .Values.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
