apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ default "telegraf" .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "telegraf.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "telegraf.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ default "registry.fke.fptcloud.com/a6762c5a-56d1-4285-b4bc-b61177a171e1/telegraf:latest" .Values.image }}
        imagePullPolicy: Always
        resources: {}
        env: {{ toYaml .Values.env | nindent 8 }}
      imagePullSecrets: 
      - name: {{ .Release.Name }}-key


